### ISSUE TITLE
Make CxPlatVector actually cross platform instead of using std::vector on non-windows platforms

### ISSUE THREAD

**Issue by csujedihy** [microsoft/cxplat#40]
We currently have a wrapper cxplatvector class for karray which is a simple C++ typedef of std::vector for non-kernel platforms.

There's an important difference between the 2 libs:
karray does not throw exceptions and thus functions that can fail with have a return value like append(), it fails when memory allocation fails.

std::vector throws an exception in this case.

This difference makes it hard for the consumers when it needs to be compiled for both kernel and usermode because in usermode, since we use std::vector, `append()` returns void but in kernel mode it returns a boolean.

We need to have real platform specific code for `new.h` (what uses it?) and `ntintsafe.h` (integer multiplication).

**Comment by nibanks** [comment]
@csujedihy can this be closed now?

**Comment by csujedihy** [comment]
@nibanks yes
